name: CI Workflow

on:
  push:
    branches:
      - "*"  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch
      - production

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run lint-staged
      - name: Run lint-staged
        run: npx lint-staged

      # Run tests 
      - name: Run tests
        run: npm test
